# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9ecd290b810eafcb26c39982a024f55a"
name = "product-listing"
handle = "product-listing-18"
application_url = "https://grade-thank-super-height.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "store1-bhatianirudh.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://grade-thank-super-height.trycloudflare.com/auth/callback",
  "https://grade-thank-super-height.trycloudflare.com/auth/shopify/callback",
  "https://grade-thank-super-height.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
